home:
    path: /
    controller: App\Controller\HomeController::indexAction

discipline:
    path: /d/{slug}
    controller: App\Controller\DisciplineController::indexAction

playlist:
    path: /p/{discipline_slug}/{playlist_slug}
    controller: App\Controller\PlaylistController::indexAction

video:
    path: /v/{discipline_slug}/{playlist_slug}/{video_slug}
    controller: App\Controller\VideoController::indexAction

sitemap:
    path: /sitemap
    controller: App\Controller\SitemapController::sitemapAction

article:
    path: /artikkel/{topic}
    controller: App\Controller\ArticleController::indexAction
