home:
    path: /
    controller: App\Controller\HomeController::indexAction

discipline:
    path: /d/{slug}
    controller: App\Controller\DisciplineController::indexAction

playlist:
    path: /p/{discipline_slug}/{playlist_slug}
    controller: App\Controller\PlaylistController::indexAction

video:
    path: /v/{discipline_slug}/{playlist_slug}/{video_slug}
    controller: App\Controller\VideoController::indexAction

sitemap:
    path: /sitemap
    controller: App\Controller\SitemapController::sitemapAction

article:
    path: /artikkel/{discipline_slug}/{topic}
    controller: App\Controller\ArticleController::indexAction

articles:
    path: /artikler
    controller: App\Controller\ArticleController::listAction

about:
    path: /about
    controller: App\Controller\AboutController::aboutAction

faq:
    path: /faq
    controller: App\Controller\AboutController::faqAction
